apiVersion: apps/v1
kind: Deployment
metadata:
  name: ce7-grp-2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ce7-grp-2-app
  template:
    metadata:
      labels:
        app: ce7-grp-2-app
    spec:
      containers:
      - name: ce7-grp-2-container
        image: ${ECR_REPOSITORY_URL}:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ce7-grp-2-app
spec:
  type: NodePort
  selector:
    app: ce7-grp-2-app
  ports:
  - port: 80
    targetPort: 80
